zuihou:
#    ip: 127.0.0.1
#    port: 3306
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#  redis:
#    ip: 127.0.0.1
#    port: 16379
#    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

logging:
  io.seata: debug
  org.springframework.cloud.alibaba.seata.web: debug

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${zuihou.mysql.ip}:${zuihou.mysql.port}/${zuihou.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull
